## NumPy (Numerical Computing Library for Python)

NumPy (Numerical Python) is a library for working with arrays and mathematical operations in Python. It is a fundamental package for scientific computing with Python, providing support for large, multi-dimensional arrays and matrices, along with a wide range of high-performance mathematical functions to manipulate them.

In [1]:
import numpy as np

In [2]:
# 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [3]:
# Indexing
print(arr1[0])

# Slicing
print(arr1[1:3])

1
[2 3]


In [24]:
#Accessing rows
#[row,element]
b= np.array([[1,2,3],[4,5,6]])

print(b[1,0])

#3D
#[array,row,element]
c= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,6]]])

print(c[1,1,2]) #6

#negative indexing
print(b[0,-2]) #2

4
6
2


In [25]:
#slicing the array
#[start:end:step]

a = np.array([1,2,3,4,5,1,7])
print(a[1:6:2])
print(a[2:-1])

#2D
b= np.array([[1,2,3],[4,5,6]])

print(b[1, 1:]) #[row,slice elements]

print(b[0: , 2]) #[starting row till end, get 2nd element from all rows]

cd= b[0:2,0:2:1]
print(cd)

[2 4 1]
[3 4 5 1]
[5 6]
[3 6]
[[1 2]
 [4 5]]


In [26]:
#datatypes

sd = np.array(['apple', 'banana', 'cherry'])

print(sd)
print(sd.dtype)

convert = sd.astype('S')
print(convert)
print(convert.dtype)

id= np.array([1,2,3])
fl = id.astype('f')
print(fl)
print(fl.dtype)

f= np.array([0.7,1.5,5.7])
x= f.astype('i')
print(x)
print(x.dtype)

['apple' 'banana' 'cherry']
<U6
[b'apple' b'banana' b'cherry']
|S6
[1. 2. 3.]
float32
[0 1 5]
int32


In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

** Built-In Methods**

***arange***

Return evenly spaced values within a given interval.

In [5]:
print(np.arange(0,10))
print(np.arange(0,11,2))

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]


***zeros and ones***

Generate arrays of zeros or ones

In [6]:
print(np.zeros(3))
print(np.zeros((5,5)))

[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
print(np.ones(3))
print(np.ones((3,3)))

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


***linspace***
Return evenly spaced numbers over a specified interval.

In [8]:
print(np.linspace(0,10,3))
print(np.linspace(0,10,50))

[ 0.  5. 10.]
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


***eye***

Creates an identity matrix

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
#copy vs view

a1= np.array([2,3,5,7])
ca1= a1.copy()  #copies the elements and stores in ca1 array 
a1[1]= 4

print(a1) #replaces value of first element by 4

print(ca1) # doesnt replace the modified value 
va1= a1.view()
print(va1)   #replaces the value in both arrays(the original, view array)

print("checking base values")
print( va1.base) #doesnot own the data
print(ca1.base) #owns the data

[2 4 5 7]
[2 3 5 7]
[2 4 5 7]
checking base values
[2 4 5 7]
None


**Random**

***rand***
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [10]:
# Generate a 2x3 array of random numbers
random_array = np.random.rand(2, 3)
print(random_array)

[[0.5273039  0.21889734 0.56960952]
 [0.16044647 0.65681605 0.53174591]]


***randn***

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [11]:
# Generate a 2x3 array of random numbers from a normal distribution
random_array = np.random.randn(2, 3)
print(random_array)

[[ 0.30045202 -1.57760536  1.43846951]
 [-0.45802339  0.12164249  0.00264544]]


***randint***
Return random integers from `low` (inclusive) to `high` (exclusive).

In [12]:
# Generate a 2x3 array of random integers between 0 and 10
random_array = np.random.randint(0, 10, size=(2, 3))
print(random_array)

[[5 7 0]
 [9 4 4]]


***choice***
Generates an array of the given shape and populates it with random samples from the specified array.

In [13]:
# Generate a 2x3 array of random samples from the array [1, 2, 3, 4, 5]
random_array = np.random.choice([1, 2, 3, 4, 5], size=(2, 3))
print(random_array)

[[5 2 2]
 [5 4 1]]


***seed***
Sets the seed for the random number generator.

In [16]:
# Set the seed for the random number generator
np.random.seed(5)

# Generate a 2x3 array of random numbers
random_array = np.random.rand(2, 3)
print(random_array)

[[0.22199317 0.87073231 0.20671916]
 [0.91861091 0.48841119 0.61174386]]


**max,min,argmax,argmin**

In [17]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [19]:
ranarr

array([27, 48, 30, 16,  7, 12, 15, 49, 39, 16], dtype=int32)

In [18]:
print(ranarr.max())
print(ranarr.argmax())
print(ranarr.min())
print(ranarr.argmin())

49
7
7
4


**Shape**

Shape is an attribute that arrays have (not a method):

In [20]:
# Vector
arr.shape

(25,)

In [21]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [22]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [28]:
#shape and reshape of an array

b= np.array([[1,2,3],[4,5,6]])
print(b.shape)

print(b.reshape(1,6))
print(b.reshape(3,2))

(2, 3)
[[1 2 3 4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [29]:
#iterating arrays

ar= np.array([[1,2,3],[7,9,10]])
print(ar)
for x in ar:
    for y in x:
        print(x,y)
        
        
ar3= np.array([[[1,2,3],[7,9,10]],[[1,2,3],[7,9,10]]])
for x in ar3:
    for y in x:
        for z in y:
         print(x,y,z)

[[ 1  2  3]
 [ 7  9 10]]
[1 2 3] 1
[1 2 3] 2
[1 2 3] 3
[ 7  9 10] 7
[ 7  9 10] 9
[ 7  9 10] 10
[[ 1  2  3]
 [ 7  9 10]] [1 2 3] 1
[[ 1  2  3]
 [ 7  9 10]] [1 2 3] 2
[[ 1  2  3]
 [ 7  9 10]] [1 2 3] 3
[[ 1  2  3]
 [ 7  9 10]] [ 7  9 10] 7
[[ 1  2  3]
 [ 7  9 10]] [ 7  9 10] 9
[[ 1  2  3]
 [ 7  9 10]] [ 7  9 10] 10
[[ 1  2  3]
 [ 7  9 10]] [1 2 3] 1
[[ 1  2  3]
 [ 7  9 10]] [1 2 3] 2
[[ 1  2  3]
 [ 7  9 10]] [1 2 3] 3
[[ 1  2  3]
 [ 7  9 10]] [ 7  9 10] 7
[[ 1  2  3]
 [ 7  9 10]] [ 7  9 10] 9
[[ 1  2  3]
 [ 7  9 10]] [ 7  9 10] 10


In [30]:
#iterating each element using nditer()

ar3= np.array([[[1,2,3],[7,9,10]],[[1,2,3],[7,9,10]]])
for x in np.nditer(ar3):
    print(x)
    
    
#iterating with different datatypes

a = np.array([1,2,3])
print(a.dtype)

#output of the resulting array is string. 
#buffered creates an extra space for the string output since it doesnt change the dataype of element inplace

for x in np.nditer(a, flags=['buffered'], op_dtypes=['S']):
    print(x)
    
print(x.dtype)


#iterating with different stepsize

b= np.array([[1,2,3,4,5],[7,9,10,11,12]])
print("sliced array")
for x in np.nditer(b[:,1:9:2]):
    print(x)

1
2
3
7
9
10
1
2
3
7
9
10
int64
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
|S21
sliced array
2
4
9
11


In [31]:
#iter gives the list elements without index, enumerate gives elements with index
list1 = np.array([1,2,3,4])
for idx, num in enumerate(list1):
    print(idx, num)
print(type(idx))
print(type(num))
    
#using ndenumerate, return indexes is a tuple

list1 = np.array([[1,2,3,4],[5,6,7,8]])
for idx, num in np.ndenumerate(list1):
    print(idx, num)
    
print(type(idx))
print(type(num))

0 1
1 2
2 3
3 4
<class 'int'>
<class 'numpy.int64'>
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
<class 'tuple'>
<class 'numpy.int64'>


In [32]:
#Joining arrays

#A. using concatenate

a= np.array([1,2,3,4])
b= np.array([5,6,7,8])

resultingarr = np.concatenate((a,b))
print(resultingarr)

#joining 2D array along an axis

a= np.array([[1,2,3],[11,12,13]])
b= np.array([[5,6,7],[14,15,16]])

resultingarr = np.concatenate((a,b),axis =1)
print(resultingarr)

#B. using stack function

a= np.array([1,2,3,4])
b= np.array([5,6,7,8])

print("resulting array using stack")
resultingarr = np.stack((a,b),axis = 1)
print(resultingarr)

#hstack - stacks along rows

print("resulting array using hstack")
resultingarr = np.hstack((a,b))
print(resultingarr)

#vstack - stacks along columns

print("resulting array using vstack")
resultingarr = np.vstack((a,b))
print(resultingarr)

#vstack - stacks along depth/height

print("resulting array using dstack")
resultingarr = np.dstack((a,b))
print(resultingarr)

[1 2 3 4 5 6 7 8]
[[ 1  2  3  5  6  7]
 [11 12 13 14 15 16]]
resulting array using stack
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
resulting array using hstack
[1 2 3 4 5 6 7 8]
resulting array using vstack
[[1 2 3 4]
 [5 6 7 8]]
resulting array using dstack
[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [33]:
#splitting arrays split(array, into how many arrays)

ar = np.array([1,11,2,3,4,5,6])

sar = np.array_split(ar,3)
print(sar[0],sar[1],sar[2])

#splitting 2d array

a= np.array([[[1,2,3,4],[11,12,13,4]],[[7,3,9,1],[1,4,6,7]]])


sa= np.array_split(a,4)
print(sa[0],sa[1],sa[2],sa[3])



#we get an error here as "split" method will not adjust elements. works only when equal ditribution of elements are present.
arr = np.split(ar,3)
print(arr[0])

[ 1 11  2] [3 4] [5 6]
[[[ 1  2  3  4]
  [11 12 13  4]]] [[[7 3 9 1]
  [1 4 6 7]]] [] []


ValueError: array split does not result in an equal division

In [34]:
#array search

a= np.array([[1,2,3],[4,5,6]])

b= np.array([6,7,8,9])

search = np.where(a==2)
print("A is located at",search)

search = np.where(b==8)
print(search)


A is located at (array([0]), array([1]))
(array([2]),)


In [35]:
#searchsorted: binary search- inserts given value in sorted order and returns index of the value inserted.


b= np.array([6,7,8,9,11])

insert = np.searchsorted(b,10)

print(insert)


b= np.array([6,7,8,9,7,10,11])


insert = np.searchsorted(b,9,side="right")

print(insert)

4
5
